[package]
name = "encodedlux/sling"
description = "A modern and reactive backpack system for Roblox."
version = "0.1.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/encodedlux/sling"
exclude = ["**"]
include = [
    "LICENSE",
    "README.md",
    "src",
    "src/**",
    "default.project.json",
    "wally.toml",
]

[dependencies]
vide = "centau/vide@0.4.0"
topbarplus = "1foreverhd/topbarplus@3.4.0"
